version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build-test:
    docker:
      - image: cimg/node:16.17.0
    
    steps:
      - checkout
      - node/install:
          node-version: '16.13'
      - node/install-packages:
          cache-path: ~/project/node_modules

      - run: npm run build
      - run: npm test

workflows:
  build:
    jobs:
      - build-test:
          filters:
            branches:
              only:
                - cicleci