version: 2.1

orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6
  docker: circleci/docker@2.1.4

jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: slimane2/joke-app-circleci
      - docker/push:
          digest-path: /tmp/digest.txt
          image: slimane2/joke-app-circleci
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

workflows:
  build:
    jobs:
      - node/test:
          matrix:
            parameters:
              version:
                - "16.15"
                - "14.19"
                - "12.13"
          filters:
            branches:
              only:
                - cicleci
    
      - node/run:
          npm-run: build
          filters:
            branches:
              only:
                - cicleci
      
      - heroku/deploy-via-git:
          app-name: joke-app-circleci-v1
  commit:
    jobs:
      - build-and-push