name: Test workflow

on:
  push:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - run: npm ci
      - run: npm run build
      - run: npm test